# Generated by Django 4.1.6 on 2023-05-02 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения')),
                ('departure_city', models.CharField(max_length=255, verbose_name='Город отправления')),
                ('destination_city', models.CharField(max_length=255, verbose_name='Город назначения')),
                ('address', models.CharField(max_length=512, verbose_name='ПВЗ или адрес для курьера')),
                ('height', models.IntegerField(verbose_name='Высота коробки, мм')),
                ('width', models.IntegerField(verbose_name='Ширина коробки, мм')),
                ('depth', models.IntegerField(verbose_name='Глубина коробки, мм')),
                ('weight', models.IntegerField(verbose_name='Вес поссылки в килограммах')),
                ('start_date', models.DateField(verbose_name='Дата передачи в доставку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('cost_of_delivery', models.IntegerField(blank=True, null=True, verbose_name='Стоимость доставки')),
            ],
            options={
                'verbose_name': 'Данные доставки',
                'verbose_name_plural': 'Данные доставок',
            },
        ),
        migrations.CreateModel(
            name='PickPoint',
            fields=[
                ('id', models.CharField(max_length=20, verbose_name='Код города в Боксберри')),
                ('center_geo', models.CharField(max_length=64, verbose_name='Геометка центральной точки')),
                ('pick_point', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код точки приема заказа')),
                ('short_name', models.CharField(max_length=4, verbose_name='Короткое название города')),
                ('full_name', models.CharField(max_length=64, verbose_name='Полное название города')),
            ],
            options={
                'verbose_name': 'Точка приема посылок',
                'verbose_name_plural': 'Точки приема посылок',
            },
        ),
    ]
