# Generated by Django 4.1.6 on 2023-05-02 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('depth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Product Boxberry',
                'verbose_name_plural': 'Products Boxberry',
                'db_table': 'boxberry_products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('vid', models.IntegerField(choices=[(1, 'ПВЗ')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Тип доставки')),
                ('destination_point', models.CharField(max_length=10)),
                ('departure_point', models.CharField(max_length=10)),
                ('customer_fio', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(11)])),
                ('customer_email', models.EmailField(max_length=254)),
                ('track_number', models.CharField(blank=True, max_length=64)),
                ('order_status', models.CharField(default='В обработке', max_length=255)),
                ('items', models.ManyToManyField(related_name='products_list', to='orders.products', verbose_name='Список товаров')),
            ],
            options={
                'verbose_name': 'Order Boxberry',
                'verbose_name_plural': 'Orders Boxberry',
                'db_table': 'boxberry_orders',
            },
        ),
    ]
